In [1]:
import numpy as np

## DataTypes and Attributes

In [2]:
a1 = np.array([1, 3, 4])
a1

array([1, 3, 4])

In [3]:
a2 = np.array([[1,3,4], [5,6,7]])
a2

array([[1, 3, 4],
       [5, 6, 7]])

In [4]:
a3 = np.array([[[3,4,5],
              [5,8,9],
              [3,6,9]],
             [[3,6,9],
             [6,8,1],
             [5,8,7]]])
a3

array([[[3, 4, 5],
        [5, 8, 9],
        [3, 6, 9]],

       [[3, 6, 9],
        [6, 8, 1],
        [5, 8, 7]]])

In [5]:
a3.shape

(2, 3, 3)

In [6]:
type(a3)

numpy.ndarray

In [7]:
sample_array = np.array([1, 2, 3])

In [8]:
sample_array

array([1, 2, 3])

In [9]:
sample_array.dtype

dtype('int64')

In [10]:
sample_array.size

3

In [11]:
ones = np.ones((2, 3))
ones

array([[1., 1., 1.],
       [1., 1., 1.]])

In [12]:
ones

array([[1., 1., 1.],
       [1., 1., 1.]])

In [13]:
type(ones)

numpy.ndarray

In [14]:
zeros = np.zeros((2, 3))
zeros

array([[0., 0., 0.],
       [0., 0., 0.]])

In [15]:
range_array = np.arange(0, 10, 2)
range_array

array([0, 2, 4, 6, 8])

In [16]:
random_array = np.random.randint(0, 10, 6)
random_array

array([6, 7, 1, 3, 9, 0])

In [17]:
random_array_1 = np.random.randint(0, 10, size=(3, 5))
random_array_1

array([[2, 3, 0, 1, 4],
       [5, 5, 9, 2, 8],
       [1, 0, 7, 0, 8]])

In [18]:
random_array.size

6

In [19]:
random_array.shape

(6,)

In [20]:
random_array_2 = np.random.random((3, 5))
random_array_2

array([[0.63690672, 0.39163521, 0.20918749, 0.99608706, 0.56213934],
       [0.96963864, 0.00241345, 0.86791434, 0.19493483, 0.74355745],
       [0.9168795 , 0.74549156, 0.90945151, 0.16124521, 0.88932228]])

In [21]:
random_array_2.shape

(3, 5)

In [22]:
random_array_3 = np.random.rand(3, 5)
random_array_3

array([[0.15212489, 0.20334331, 0.42723545, 0.11273936, 0.91634979],
       [0.03672017, 0.44357452, 0.43854324, 0.60961771, 0.30463298],
       [0.23406766, 0.80276986, 0.42307178, 0.20713769, 0.6247363 ]])

In [23]:
random_array_3.shape

(3, 5)

In [24]:
#pseudo-ransom numbers
np.random.seed(seed=0)
random_array_4 = np.random.randint(5, 10, size=(3, 5))
random_array_4

array([[9, 5, 8, 8, 8],
       [6, 8, 7, 9, 5],
       [5, 9, 7, 6, 5]])

## Viewing Arrays and Matrices

In [25]:
a1

array([1, 3, 4])

In [26]:
a2

array([[1, 3, 4],
       [5, 6, 7]])

In [27]:
a3

array([[[3, 4, 5],
        [5, 8, 9],
        [3, 6, 9]],

       [[3, 6, 9],
        [6, 8, 1],
        [5, 8, 7]]])

In [28]:
a1[0]

1

In [29]:
a3[1, 0, 2]

9

In [30]:
a3

array([[[3, 4, 5],
        [5, 8, 9],
        [3, 6, 9]],

       [[3, 6, 9],
        [6, 8, 1],
        [5, 8, 7]]])

In [31]:
a3[:2, :2, :2]

array([[[3, 4],
        [5, 8]],

       [[3, 6],
        [6, 8]]])

In [32]:
a4 = np.random.randint(10, size=(2,3,4,5))

In [33]:
a4

array([[[[1, 5, 9, 8, 9],
         [4, 3, 0, 3, 5],
         [0, 2, 3, 8, 1],
         [3, 3, 3, 7, 0]],

        [[1, 9, 9, 0, 4],
         [7, 3, 2, 7, 2],
         [0, 0, 4, 5, 5],
         [6, 8, 4, 1, 4]],

        [[9, 8, 1, 1, 7],
         [9, 9, 3, 6, 7],
         [2, 0, 3, 5, 9],
         [4, 4, 6, 4, 4]]],


       [[[3, 4, 4, 8, 4],
         [3, 7, 5, 5, 0],
         [1, 5, 9, 3, 0],
         [5, 0, 1, 2, 4]],

        [[2, 0, 3, 2, 0],
         [7, 5, 9, 0, 2],
         [7, 2, 9, 2, 3],
         [3, 2, 3, 4, 1]],

        [[2, 9, 1, 4, 6],
         [8, 2, 3, 0, 0],
         [6, 0, 6, 3, 3],
         [8, 8, 8, 2, 3]]]])

In [34]:
a4[1, 1, 1, 4]

2

In [35]:
a4[1, 2, 3, 4]

3

## Manipulating & Comparing Arrays

### Arithmetic

In [36]:
ones = np.ones(3)
ones

array([1., 1., 1.])

In [37]:
a1

array([1, 3, 4])

In [38]:
a1 + ones

array([2., 4., 5.])

In [39]:
a1 - ones

array([0., 2., 3.])

In [40]:
a1 * a3

array([[[ 3, 12, 20],
        [ 5, 24, 36],
        [ 3, 18, 36]],

       [[ 3, 18, 36],
        [ 6, 24,  4],
        [ 5, 24, 28]]])

In [41]:
a2

array([[1, 3, 4],
       [5, 6, 7]])

In [42]:
a2[0, 1]

3

In [43]:
a2[0:1] * a3

array([[[ 3, 12, 20],
        [ 5, 24, 36],
        [ 3, 18, 36]],

       [[ 3, 18, 36],
        [ 6, 24,  4],
        [ 5, 24, 28]]])

In [44]:
a1 / ones

array([1., 3., 4.])

In [45]:
a1 // ones

array([1., 3., 4.])

In [46]:
a2 ** 2

array([[ 1,  9, 16],
       [25, 36, 49]])

In [47]:
np.square(a2)

array([[ 1,  9, 16],
       [25, 36, 49]])

In [48]:
a1 + a2

array([[ 2,  6,  8],
       [ 6,  9, 11]])

In [49]:
np.add(a1, a2)

array([[ 2,  6,  8],
       [ 6,  9, 11]])

In [50]:
np.exp(a2)

array([[   2.71828183,   20.08553692,   54.59815003],
       [ 148.4131591 ,  403.42879349, 1096.63315843]])

In [51]:
a1 % ones

array([0., 0., 0.])

In [52]:
a2 % a1

array([[0, 0, 0],
       [0, 0, 3]])

In [53]:
np.log(a1)

array([0.        , 1.09861229, 1.38629436])

## Aggregation
### Aggregation is performing operation on a number of things

In [54]:
listy_list = [1, 2, 3]
type(listy_list)

list

### Use python's methods (`sum()`) on python datatypes and Numpy's method on Numpy arrays (`np.sum()`)

In [55]:
massive_array = np.random.random(100000)
massive_array.size

100000

In [56]:
massive_array[:5]

array([0.70373728, 0.28847644, 0.43328806, 0.75610669, 0.39609828])

In [57]:
%timeit sum(massive_array) #Python's sum()
%timeit np.sum(massive_array) # Numpy's np.sum()

7.78 ms ± 87.3 µs per loop (mean ± std. dev. of 7 runs, 100 loops each)
48.3 µs ± 1.51 µs per loop (mean ± std. dev. of 7 runs, 10,000 loops each)


In [58]:
a2

array([[1, 3, 4],
       [5, 6, 7]])

In [59]:
np.max(a2)

7

In [60]:
np.std(a2) # Numpy's standard deviation

1.9720265943665387

In [61]:
np.square(np.std(a2))

3.888888888888889

In [62]:
np.var(a2) # Numpy's variance

3.8888888888888893

In [63]:
# Demo of an std and var
high_var_array = np.array([1, 200, 400, 2000, 5000])
low_var_array = np.array([2, 4, 6, 8, 10])

In [64]:
np.std(high_var_array), np.std(low_var_array)

(1878.5611941057443, 2.8284271247461903)

In [65]:
np.var(high_var_array), np.var(low_var_array)

(3528992.16, 8.0)

### Reshaping & Transposing

In [66]:
a1

array([1, 3, 4])

In [67]:
a2

array([[1, 3, 4],
       [5, 6, 7]])

In [68]:
a3

array([[[3, 4, 5],
        [5, 8, 9],
        [3, 6, 9]],

       [[3, 6, 9],
        [6, 8, 1],
        [5, 8, 7]]])

In [69]:
a2.reshape(2, 3, 1)

array([[[1],
        [3],
        [4]],

       [[5],
        [6],
        [7]]])

In [70]:
a2 

array([[1, 3, 4],
       [5, 6, 7]])

In [71]:
a2_reshape = a2.reshape(2, 3, 1)

In [72]:
a2_reshape

array([[[1],
        [3],
        [4]],

       [[5],
        [6],
        [7]]])

In [73]:
a2_reshape * a3

array([[[ 3,  4,  5],
        [15, 24, 27],
        [12, 24, 36]],

       [[15, 30, 45],
        [36, 48,  6],
        [35, 56, 49]]])

### Transpose

In [74]:
a2

array([[1, 3, 4],
       [5, 6, 7]])

In [75]:
a2.T

array([[1, 5],
       [3, 6],
       [4, 7]])

## Dot Product

In [76]:
np.random.seed(0)
mat1 = np.random.randint(10, size=(5, 3))
mat2 = np.random.randint(10, size=(5, 3))
mat1, mat2

(array([[5, 0, 3],
        [3, 7, 9],
        [3, 5, 2],
        [4, 7, 6],
        [8, 8, 1]]),
 array([[6, 7, 7],
        [8, 1, 5],
        [9, 8, 9],
        [4, 3, 0],
        [3, 5, 0]]))

In [77]:
mat1 * mat2

array([[30,  0, 21],
       [24,  7, 45],
       [27, 40, 18],
       [16, 21,  0],
       [24, 40,  0]])

In [78]:
mat1.shape, mat2.shape

((5, 3), (5, 3))

In [79]:
np.dot(mat1.T, mat2)

array([[121, 114,  77],
       [153, 108,  80],
       [135,  69,  84]])

In [80]:
mat3 = np.dot(mat1, mat2.T)
mat3

array([[ 51,  55,  72,  20,  15],
       [130,  76, 164,  33,  44],
       [ 67,  39,  85,  27,  34],
       [115,  69, 146,  37,  47],
       [111,  77, 145,  56,  64]])

In [81]:
mat3.shape

(5, 5)

## Dot product example

In [82]:
np.random.seed(0)
#Number of jars sold
sales_amount = np.random.randint(20, size=(5, 3))
sales_amount

array([[12, 15,  0],
       [ 3,  3,  7],
       [ 9, 19, 18],
       [ 4,  6, 12],
       [ 1,  6,  7]])

In [83]:
import pandas as pd

In [84]:
weekly_sales = pd.DataFrame(sales_amount,
                             index=['Mon', 'Tue', 'Wed', 'Thur', 'Fri'],
                             columns=['Almond Butter', 'Peanut Butter', 'Cashew butter'])
weekly_sales

Almond Butter  Peanut Butter  Cashew butter
Mon              12             15              0
Tue               3              3              7
Wed               9             19             18
Thur              4              6             12
Fri               1              6              7

In [85]:
# Create price array
prices = np.array([10, 8, 12])
prices

array([10,  8, 12])

In [86]:
# Create butter_prices DataFrame
butter_prices = pd.DataFrame(prices.reshape(1, 3),
                             index=['Prices'],
                             columns=['Almond Butter', 'Peanut Butter', 'Cashew butter'])
butter_prices

Almond Butter  Peanut Butter  Cashew butter
Prices             10              8             12

In [87]:
# Total Sales
total_sales = prices.dot(sales_amount.T)
total_sales

array([240, 138, 458, 232, 142])

In [88]:
butter_prices

Almond Butter  Peanut Butter  Cashew butter
Prices             10              8             12

In [89]:
butter_prices.shape, weekly_sales.shape

((1, 3), (5, 3))

In [90]:
weekly_sales

Almond Butter  Peanut Butter  Cashew butter
Mon              12             15              0
Tue               3              3              7
Wed               9             19             18
Thur              4              6             12
Fri               1              6              7

In [91]:
# Daily sales
daily_sales = butter_prices.dot(weekly_sales.T)
daily_sales

Mon  Tue  Wed  Thur  Fri
Prices  240  138  458   232  142

In [92]:
#Adding the Total column on the weekly_sales table
weekly_sales['Totals ($)'] = daily_sales.T
weekly_sales

Almond Butter  Peanut Butter  Cashew butter  Totals ($)
Mon              12             15              0         240
Tue               3              3              7         138
Wed               9             19             18         458
Thur              4              6             12         232
Fri               1              6              7         142

### Comparison operators

In [93]:
a1 

array([1, 3, 4])

In [94]:
a2

array([[1, 3, 4],
       [5, 6, 7]])

In [95]:
a1 > a2

array([[False, False, False],
       [False, False, False]])

In [96]:
bool_array = a1 >= a2
bool_array

array([[ True,  True,  True],
       [False, False, False]])

In [97]:
type(bool_array), bool_array.dtype

(numpy.ndarray, dtype('bool'))

## Sorting arrays

In [98]:
random_array = np.random.randint(10, size=(3, 5))
random_array

array([[7, 8, 1, 5, 9],
       [8, 9, 4, 3, 0],
       [3, 5, 0, 2, 3]])

In [99]:
np.sort(random_array)

array([[1, 5, 7, 8, 9],
       [0, 3, 4, 8, 9],
       [0, 2, 3, 3, 5]])

In [100]:
random_array

array([[7, 8, 1, 5, 9],
       [8, 9, 4, 3, 0],
       [3, 5, 0, 2, 3]])

In [101]:
np.argsort(random_array, axis=0)

array([[2, 2, 2, 2, 1],
       [0, 0, 0, 1, 2],
       [1, 1, 1, 0, 0]])

In [102]:
a1

array([1, 3, 4])

In [103]:
np.argsort(a1)

array([0, 1, 2])

In [104]:
np.argmax(a1)

2

In [105]:
np.argmin(a1)

0

## Practical Example

In [106]:
# Run the markdown <img src='images/panda.png'/>

<img src='images/panda.png'/>

## Turn an image into numpy array

In [107]:
from matplotlib.image import imread

panda = imread('images/panda.png')
type(panda)

numpy.ndarray

In [108]:
panda

array([[[0.05490196, 0.10588235, 0.06666667],
        [0.05490196, 0.10588235, 0.06666667],
        [0.05490196, 0.10588235, 0.06666667],
        ...,
        [0.16470589, 0.12941177, 0.09411765],
        [0.16470589, 0.12941177, 0.09411765],
        [0.16470589, 0.12941177, 0.09411765]],

       [[0.05490196, 0.10588235, 0.06666667],
        [0.05490196, 0.10588235, 0.06666667],
        [0.05490196, 0.10588235, 0.06666667],
        ...,
        [0.16470589, 0.12941177, 0.09411765],
        [0.16470589, 0.12941177, 0.09411765],
        [0.16470589, 0.12941177, 0.09411765]],

       [[0.05490196, 0.10588235, 0.06666667],
        [0.05490196, 0.10588235, 0.06666667],
        [0.05490196, 0.10588235, 0.06666667],
        ...,
        [0.16470589, 0.12941177, 0.09411765],
        [0.16470589, 0.12941177, 0.09411765],
        [0.16470589, 0.12941177, 0.09411765]],

       ...,

       [[0.13333334, 0.07450981, 0.05490196],
        [0.12156863, 0.0627451 , 0.04313726],
        [0.10980392, 0

In [109]:
panda.size, panda.shape, panda.ndim

(24465000, (2330, 3500, 3), 3)

### Display car

<img src='images/car-photo.png'/>

In [110]:
car = imread('images/car-photo.png')
type(car)

numpy.ndarray

In [111]:
car

array([[[0.5019608 , 0.50980395, 0.4862745 , 1.        ],
        [0.3372549 , 0.34509805, 0.30588236, 1.        ],
        [0.20392157, 0.21568628, 0.14901961, 1.        ],
        ...,
        [0.64705884, 0.7058824 , 0.54901963, 1.        ],
        [0.59607846, 0.63529414, 0.45882353, 1.        ],
        [0.44705883, 0.47058824, 0.3372549 , 1.        ]],

       [[0.44313726, 0.43529412, 0.40392157, 1.        ],
        [0.3137255 , 0.31764707, 0.27450982, 1.        ],
        [0.2       , 0.21176471, 0.14117648, 1.        ],
        ...,
        [0.5058824 , 0.5372549 , 0.4117647 , 1.        ],
        [0.49803922, 0.52156866, 0.39607844, 1.        ],
        [0.4       , 0.42745098, 0.34117648, 1.        ]],

       [[0.39607844, 0.38039216, 0.34117648, 1.        ],
        [0.31764707, 0.3137255 , 0.27450982, 1.        ],
        [0.28627452, 0.29411766, 0.24705882, 1.        ],
        ...,
        [0.44705883, 0.45882353, 0.32156864, 1.        ],
        [0.45882353, 0.482352

## Display Dog

<img src='images/dog-photo.png'/>

In [112]:
dog = imread('images/dog-photo.png')
type(dog)

numpy.ndarray

In [113]:
dog

array([[[0.70980394, 0.80784315, 0.88235295, 1.        ],
        [0.72156864, 0.8117647 , 0.8862745 , 1.        ],
        [0.7411765 , 0.8156863 , 0.8862745 , 1.        ],
        ...,
        [0.49803922, 0.6862745 , 0.8392157 , 1.        ],
        [0.49411765, 0.68235296, 0.8392157 , 1.        ],
        [0.49411765, 0.68235296, 0.8352941 , 1.        ]],

       [[0.69411767, 0.8039216 , 0.8862745 , 1.        ],
        [0.7019608 , 0.8039216 , 0.88235295, 1.        ],
        [0.7058824 , 0.80784315, 0.88235295, 1.        ],
        ...,
        [0.5019608 , 0.6862745 , 0.84705883, 1.        ],
        [0.49411765, 0.68235296, 0.84313726, 1.        ],
        [0.49411765, 0.68235296, 0.8392157 , 1.        ]],

       [[0.6901961 , 0.8       , 0.88235295, 1.        ],
        [0.69803923, 0.8039216 , 0.88235295, 1.        ],
        [0.7058824 , 0.80784315, 0.88235295, 1.        ],
        ...,
        [0.5019608 , 0.6862745 , 0.84705883, 1.        ],
        [0.49803922, 0.686274

In [114]:
dog

array([[[0.70980394, 0.80784315, 0.88235295, 1.        ],
        [0.72156864, 0.8117647 , 0.8862745 , 1.        ],
        [0.7411765 , 0.8156863 , 0.8862745 , 1.        ],
        ...,
        [0.49803922, 0.6862745 , 0.8392157 , 1.        ],
        [0.49411765, 0.68235296, 0.8392157 , 1.        ],
        [0.49411765, 0.68235296, 0.8352941 , 1.        ]],

       [[0.69411767, 0.8039216 , 0.8862745 , 1.        ],
        [0.7019608 , 0.8039216 , 0.88235295, 1.        ],
        [0.7058824 , 0.80784315, 0.88235295, 1.        ],
        ...,
        [0.5019608 , 0.6862745 , 0.84705883, 1.        ],
        [0.49411765, 0.68235296, 0.84313726, 1.        ],
        [0.49411765, 0.68235296, 0.8392157 , 1.        ]],

       [[0.6901961 , 0.8       , 0.88235295, 1.        ],
        [0.69803923, 0.8039216 , 0.88235295, 1.        ],
        [0.7058824 , 0.80784315, 0.88235295, 1.        ],
        ...,
        [0.5019608 , 0.6862745 , 0.84705883, 1.        ],
        [0.49803922, 0.686274